
pub fn compute_21(
    _r: Field,
    _op_sorted_step: [Field; 21],
    _op_sorted_addr: [Field; 21],
    _op_sorted_val: [Field; 21],
    _op_sorted_op_rw: [Field; 21]
) -> Field {
    // TODO: implement
    0
}

pub fn compute_9(
    _r: Field,
    _op_sorted_step: [Field; 9],
    _op_sorted_addr: [Field; 9],
    _op_sorted_val: [Field; 9],
    _op_sorted_op_rw: [Field; 9]
) -> Field {
    // TODO: implement
    0
}


pub fn compute_7(
    _r: Field,
    _op_sorted_step: [Field; 7],
    _op_sorted_addr: [Field; 7],
    _op_sorted_val: [Field; 7],
    _op_sorted_op_rw: [Field; 7]

) -> Field {
    // TODO: implement
    0
}